### ISSUE TITLE
Copy/fork of https://github.com/yozachar/asdf-bin

### ISSUE THREAD

**Issue by epoch-chrono** [yozachar/hymnal#1]
Hi @yozachar  ,

First of all, I am sorry to create an issue here. It was the only way to contact you about this repo:
https://github.com/yozachar/asdf-bin

Could I get a copy of the main branch or a fork? It looks like it was archived/removed or isn't public anymore.
I just formatted my Mac and was re-doing my setup when I couldn't add this `asdf` plugin. 
This was useful for me when working with `asdf`.

Kind regards
Vitor Jr.

**Comment by nandgator** [comment]
Hello @epoch-chrono,

I'm sorry, I didn't keep a backup.

I switched from `asdf` to [`mise`](https://github.com/jdx/mise) (which is pretty fast and asdf compatible), but then I found myself installing `mise` with `bin`, so then, inversely, installing `bin` with `mise/asdf` didn't make sense. This is what I do now:

```bash
#!/bin/bash

BIN_VERSION=0.17.5

wget https://github.com/marcosnils/bin/releases/download/v${BIN_VERSION}/bin_${BIN_VERSION}_linux_amd64
chmod u+x ./bin_${BIN_VERSION}_linux_amd64

./bin_${BIN_VERSION}_linux_amd64 i github.com/marcosnils/bin ~/.local/bin/bin
chmod u+x ~/.local/bin/bin

rm ./bin_${BIN_VERSION}_linux_amd64

bin i github.com/jdx/mise
```

Sorry, again for breaking your workflow, but I hope this helps.

**Comment by epoch-chrono** [comment]
This `mise` tool solves all my problems! LOL!
Thank you so much for the tip!
